[tools]
node = "20"

[env]
_.file = '.env'
_.path = ['{{config_root}}/node_modules/.bin']

[hooks]
postinstall = "npm install"

[tasks.clean]
run = """
    rm -rf node_modules
    rm -rf out
"""

[tasks.build]
run = """
    npm install
    npm run compile
"""

[tasks.package]
run = "vsce package"

[tasks.publish]
run = """
vsce publish
open https://marketplace.visualstudio.com/manage/publishers/seanodell
"""
